version: "3.7"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/02_data.sql

  fastapi:
    build: ./src
    depends_on:
      - mysql
    container_name: fastapi
    command: sh -c "sleep 10; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-config ./log_config.yaml"
    volumes:
      - ./src:/usr/src/app/
      - ./integration_test:/usr/src/
    ports:
      - 8002:8000
    environment: # TODO: Bundle them into a file
      MYSQL_HOST: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
networks:
  default:
    name: fastapi
