apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: notes
spec:
  database: test
  name: notes
  schema:
    mysql:
      primaryKey: [id]
      columns:
        - name: id
          type: int
          constraints:
            notNull: true
        - name: title
          type: varchar(50)
        - name: description
          type: varchar(100)
        - name: created_at
          type: date
