apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app-fastapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: api-app

  source:
    repoURL: https://github.com/k3forx/fastapi-example
    targetRevision: master
    path: k8s/fastapi/overlays/api-app/

  destination:
    server: https://kubernetes.default.svc
    namespace: api-app

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
