apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: api-app
  namespace: argocd
spec:
  description: api-app

  sourceRepos:
    - "*"

  destinations:
    - namespace: api-app
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy

  orphanedResources:
    warn: false
