apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  template:
    spec:
      containers:
        - name: mysql
          imagePullPolicy: IfNotPresent
          image: mysql:5.7
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
