apiVersion: v1
kind: Deployment
metadata:
  name: fastapi-example
  labels:
    app: fastapi-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-example
  template:
    metadata:
      labels:
        app: fastapi-example
    spec:
      containers:
      - name: fastapi-example
        image: kanata333/fastapi-example:v1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      restartPolicy: Never
