apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system-sealed-secrets-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kube-system

  source:
    repoURL: https://github.com/k3forx/fastapi-example
    targetRevision: master
    path: k8s/sealed-secrets-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
