CREATE DATABASE IF NOT EXISTS `note-app` DEFAULT CHARSET = 'utf8mb4';

USE `note-app`;

CREATE TABLE IF NOT EXISTS `notes` (
  `id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  `user_id` INT,
  `title` VARCHAR(50),
  `description` VARCHAR(100),
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = 'InnoDB';

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  `username` VARCHAR(32) NOT NULL UNIQUE,
  `password` VARCHAR(120) NOT NULL,
  `disabled` BOOLEAN NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = 'InnoDB';
