CREATE DATABASE IF NOT EXISTS `test` DEFAULT CHARSET = 'utf8mb4';
USE `test`;
CREATE TABLE IF NOT EXISTS `notes` (
  `id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  `title` VARCHAR(50),
  `description` VARCHAR(100),
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = 'InnoDB';
