apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schemahero-system-schemahero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: schemahero-system

  source:
    repoURL: https://github.com/k3forx/fastapi-example
    targetRevision: master
    path: k8s/schemahero

  destination:
    server: https://kubernetes.default.svc
    namespace: schemahero-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
