apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/rules.yml
    scrape_configs:
      - job_name: fastapi
        static_configs:
          - targets: ["fastapi.api-app.svc.cluster.local:8000"]
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc.cluster.local:9093"
  rules.yml: |-
    groups:
    - name: FastAPI alerts
      rules:
      - alert: Application is down
        expr: up == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.job }} down"
          description: "The {{ $labels.job }} has been down for more than 5 seconds"
