apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  MYSQL_DATABASE: dGVzdA==
  MYSQL_PASSWORD: bXlzcWw=
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: bXlzcWw=
