version: 1

formatters:
  Standard:
    format: "%(asctime)-15s [%(funcName)s] %(message)s"
    datefmt: "%Y/%m/%d %I:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: Standard
    stream: ext://sys.stdout

loggers:
  testLogger:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
