apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: api
      port: 9090
      protocol: TCP
      targetPort: api
  selector:
    prometheus: prometheus
