name: integration-test

on:
  pull_request:
    paths:
      - ".github/workflows/integration-test.yaml"
      - "app/**/*.py"
      - "docker-compose.yaml"
      - "db/*.sql"
      - "!**/*.md"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/checkout@v2

      - name: Start docker containers
        run: docker-compose up -d fastapi mysql

      - name: Check endpoints
        run: ./check-api-endpoints.sh
