name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
  # release:
  #   types: [released]

jobs:
  build:
    # if: github.event.release.target_commitish == 'master'
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: false
          tags: kanata333/docker-hub-push:latest
