name: unit-test

on:
  pull_request:
    paths:
      - app/**/*.py
      - .github/workflows/unit-test.yaml

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Execute unit test
        run: |
          cd ./app
          pip install -r requirements.test.txt && \
          pip install -r requirements.txt
          pytest -v --cov --cov-report=term-missing unit_tests/
