apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: kanata333/fastapi-example:v1.5.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fastapi-configmap
            - secretRef:
                name: fastapi-secret
          resources:
            limits:
              memory: "150Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "200m"
          securityContext:
            runAsGroup: 11211
            runAsUser: 11211
            readOnlyRootFilesystem: true
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 15
            tcpSocket:
              port: 8000
