apiVersion: v1
kind: Pod
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  containers:
    - name: fastapi
      image: kanata333/fastapi-example:v1.1.0
      imagePullPolicy: Always
  restartPolicy: Never
